syntax = "proto3";

option csharp_namespace = "CrdtServer";


message CrdtId {
int32 nodeId = 1;
int64 counter = 2;
}

message CrdtElement {
CrdtId id = 1;
string value = 2;
CrdtId predecessorId = 3;
bool isDeleted = 4;
}

message InsertOperationMessage {
	string docId = 1;
	CrdtElement element = 2;
}

message DeleteOperationMessage {
	string docId = 1;
	CrdtId elementId = 2;
}

service CrdtService {
rpc DeleteOperation(stream DeleteOperationMessage) returns (stream DeleteOperationMessage);
rpc InsertOperation(stream InsertOperationMessage) returns (stream InsertOperationMessage);
}



